version: '3.7'
services:
    sql:
        container_name: Group2postgres
        image: postgres
        volumes: 
            - "~/postgres/data:/var/lib/postgresql/data"
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
    nosql:
        container_name: Group2mongo
        image: mongo
        volumes: 
            - "~/mongo/data:/data/db"
        restart: always
        ports:
            - 27017:27017